2022-03-26 11:52:14,375 INFO    MainThread:84 [wandb_setup.py:_flush():75] Loading settings from /home/jovyan/.config/wandb/settings
2022-03-26 11:52:14,375 INFO    MainThread:84 [wandb_setup.py:_flush():75] Loading settings from /home/jovyan/work/MSE-DeLearn/SW04/wandb/settings
2022-03-26 11:52:14,375 INFO    MainThread:84 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-26 11:52:14,376 INFO    MainThread:84 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-26 11:52:14,376 INFO    MainThread:84 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-03-26 11:52:14,377 INFO    MainThread:84 [wandb_init.py:_log_setup():405] Logging user logs to /home/jovyan/work/MSE-DeLearn/SW04/wandb/run-20220326_115214-24anngqh/logs/debug.log
2022-03-26 11:52:14,378 INFO    MainThread:84 [wandb_init.py:_log_setup():406] Logging internal logs to /home/jovyan/work/MSE-DeLearn/SW04/wandb/run-20220326_115214-24anngqh/logs/debug-internal.log
2022-03-26 11:52:14,378 INFO    MainThread:84 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f865150cdc0>
2022-03-26 11:52:14,378 INFO    MainThread:84 [wandb_init.py:init():439] calling init triggers
2022-03-26 11:52:14,379 INFO    MainThread:84 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.25, 'dataset': 'FashionMNIST', 'epochs': 100, 'p_in': 0, 'p_hidden': 0, 'hidden_units': 100}
2022-03-26 11:52:14,379 INFO    MainThread:84 [wandb_init.py:init():492] starting backend
2022-03-26 11:52:14,379 INFO    MainThread:84 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-26 11:52:14,393 INFO    MainThread:84 [backend.py:ensure_launched():219] starting backend process...
2022-03-26 11:52:14,401 INFO    MainThread:84 [backend.py:ensure_launched():224] started backend process with pid: 162
2022-03-26 11:52:14,402 INFO    MainThread:84 [wandb_init.py:init():501] backend started and connected
2022-03-26 11:52:14,424 INFO    MainThread:84 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-26 11:52:14,425 INFO    MainThread:84 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-26 11:52:14,426 INFO    MainThread:84 [wandb_init.py:init():565] updated telemetry
2022-03-26 11:52:14,550 INFO    MainThread:84 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-26 11:52:15,629 INFO    MainThread:84 [wandb_run.py:_on_init():1759] communicating current version
2022-03-26 11:52:15,758 INFO    MainThread:84 [wandb_run.py:_on_init():1763] got version response 
2022-03-26 11:52:15,759 INFO    MainThread:84 [wandb_init.py:init():625] starting run threads in backend
2022-03-26 11:52:16,782 INFO    MainThread:84 [wandb_run.py:_console_start():1733] atexit reg
2022-03-26 11:52:16,786 INFO    MainThread:84 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-26 11:52:16,787 INFO    MainThread:84 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-26 11:52:16,789 INFO    MainThread:84 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-26 11:52:16,790 INFO    MainThread:84 [wandb_init.py:init():664] run started, returning control to user process
2022-03-26 11:52:27,293 INFO    MainThread:84 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-26 11:52:27,293 INFO    MainThread:84 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-26 11:52:54,933 INFO    MainThread:84 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-26 11:52:55,730 INFO    MainThread:84 [wandb_setup.py:_flush():75] Loading settings from /home/jovyan/.config/wandb/settings
2022-03-26 11:52:55,731 INFO    MainThread:84 [wandb_setup.py:_flush():75] Loading settings from /home/jovyan/work/MSE-DeLearn/SW04/wandb/settings
2022-03-26 11:52:55,731 INFO    MainThread:84 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-26 11:52:55,732 INFO    MainThread:84 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-26 11:52:55,732 INFO    MainThread:84 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-03-26 11:52:55,733 INFO    MainThread:84 [wandb_init.py:_log_setup():405] Logging user logs to /home/jovyan/work/MSE-DeLearn/SW04/wandb/run-20220326_115255-3o90jn57/logs/debug.log
2022-03-26 11:52:55,734 INFO    MainThread:84 [wandb_init.py:_log_setup():406] Logging internal logs to /home/jovyan/work/MSE-DeLearn/SW04/wandb/run-20220326_115255-3o90jn57/logs/debug-internal.log
2022-03-26 11:52:55,735 INFO    MainThread:84 [wandb_init.py:init():439] calling init triggers
2022-03-26 11:52:55,735 INFO    MainThread:84 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.25, 'dataset': 'FashionMNIST', 'epochs': 100, 'p_in': 0, 'p_hidden': 0, 'hidden_units': 100}
2022-03-26 11:52:55,736 INFO    MainThread:84 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 24anngqh
2022-03-26 11:52:55,749 ERROR   MainThread:84 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 471, in init
    self._wl._global_run_stack[-1].finish()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1538, in finish
    tel.feature.finish = True
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/lib/telemetry.py", line 43, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 470, in _telemetry_callback
    self._telemetry_flush()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 481, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 73, in _publish_telemetry
    self._publish(rec)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-03-26 11:52:58,585 INFO    MainThread:84 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-26 11:52:58,586 INFO    MainThread:84 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-26 11:53:05,847 INFO    MainThread:84 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-26 11:53:05,897 ERROR   MainThread:84 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    wi.setup(kwargs)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 143, in setup
    tel.feature.set_init_tags = True
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/lib/telemetry.py", line 43, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 470, in _telemetry_callback
    self._telemetry_flush()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 481, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 73, in _publish_telemetry
    self._publish(rec)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-03-26 11:53:08,162 INFO    MainThread:84 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-26 11:53:08,163 INFO    MainThread:84 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-26 11:53:20,334 INFO    MainThread:84 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-26 11:53:20,338 INFO    MainThread:84 [wandb_run.py:_restore():1674] restore
